-- begin SAMPLE_ORDER_ITEM
alter table SAMPLE_ORDER_ITEM add constraint FK_SAMPLE_ORDER_ITEM_PRODUCT foreign key (PRODUCT_ID) references SAMPLE_PRODUCT(ID)^
create index IDX_SAMPLE_ORDER_ITEM_PRODUCT on SAMPLE_ORDER_ITEM (PRODUCT_ID)^
-- end SAMPLE_ORDER_ITEM
